# Import Libraries

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_california_housing
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score
import sqlite3

print("All libraries imported suuccessfully!")

All libraries imported suuccessfully!

# Load the DataSet

In [4]:
# Load California Housing Dataset
housing =fetch_california_housing()

#Convert to DataFrame
df = pd.DataFrame(housing.data, columns = housing.feature_names)

#Add Target column (house price)
df["Price"] = housing.target

print("Dataset loaded successfully")
print("Shape",df.shape)
df.head()

Dataset loaded successfully
Shape (20640, 9)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [6]:
conn = sqlite3.connect("california_housing.db")

In [11]:
df.to_sql("housing", conn, if_exists = "replace", index = False)
print("Data saved to the database")

Data saved to the database

In [14]:
query = """
SELECT *
FROM housing
LIMIT 5;
"""
pd.read_sql_query(query,conn)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [17]:
query = """
SELECT MedInc, HouseAge, Price
FROM housing
LIMIT 5;
"""
pd.read_sql_query(query,conn)

   MedInc  HouseAge  Price
0  8.3252      41.0  4.526
1  8.3014      21.0  3.585
2  7.2574      52.0  3.521
3  5.6431      52.0  3.413
4  3.8462      52.0  3.422

In [18]:
query = """
Select MedInc, HouseAge, Price
from housing
where Price > 3
Limit 5;
"""
pd.read_sql_query(query,conn)

   MedInc  HouseAge  Price
0  8.3252      41.0  4.526
1  8.3014      21.0  3.585
2  7.2574      52.0  3.521
3  5.6431      52.0  3.413
4  3.8462      52.0  3.422

In [20]:
query = '''
select MedInc, HouseAge, Price
From housing
order by Price ASC
Limit 5;
'''
pd.read_sql_query(query, conn)

   MedInc  HouseAge    Price
0  1.6607      16.0  0.14999
1  2.1000      19.0  0.14999
2  4.1932      52.0  0.14999
3  0.5360      36.0  0.14999
4  2.3667      39.0  0.17500

In [22]:
query = '''
select count(*) As total_records
from housing;
'''
pd.read_sql_query(query,conn)

   total_records
0          20640

In [24]:
query = '''
select AVG(Price) AS average_price
from housing;
'''
pd.read_sql_query(query,conn)

   average_price
0       2.068558

In [25]:
query = '''
select MedInc, HouseAge, Price
from housing
where price > 3 AND HouseAge < 20
LIMIT 5;
'''
pd.read_sql_query(query, conn)

    MedInc  HouseAge  Price
0  11.6017      18.0  3.926
1   7.6110       5.0  3.507
2   7.2634      12.0  3.416
3   7.0568       5.0  4.125
4   3.8958       6.0  3.011

In [26]:
query = '''
select count(*) AS missing_prices
from housing
where Price is NULL;
'''
pd.read_sql_query(query, conn)

   missing_prices
0               0

In [28]:
query = '''
select HouseAge, count(*) AS total_records,
AVG(Price) AS average_Price
from housing
Group By HouseAge
Order by HouseAge
limit 5;
'''
pd.read_sql_query(query, conn)

   HouseAge  total_records  average_Price
0       1.0              4       1.443000
1       2.0             58       2.244759
2       3.0             62       2.356436
3       4.0            191       2.292351
4       5.0            244       2.084177

In [29]:
query = '''
select *
from housing
'''
df = pd.read_sql_query(query, conn)
print("Shape", df.shape)
df.head()

Shape (20640, 9)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422